name: test macOS x86_64

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  BuildAndTest:
    runs-on: opencv-cn-mac-x86-64
    defaults:
      run:
        shell: bash
    steps:
    - name: Brief system information
      timeout-minutes: 60
      run: bash $GIT_CACHE/print_system_information.sh